### ISSUE TITLE
新着レビューらへんのリンク

### ISSUE THREAD

**Issue by kou7306** [kou7306/comict#275]
アイコン押すと飛ぶ

**Comment by kappy0713** [comment]
とりあえずユーザーアイコン押すとユーザーページに遷移するようにしたんですけど、必要ですかね？
漫画詳細へのリンクができないならユーザーも必要ないと思ったんですけど

**Comment by kohei-irohasu** [comment]
・新着レビューの漫画のアイコンをクリックで、漫画詳細へ遷移する
